using System;
using System.Collections.Generic;

namespace Comp._7211GroupProjectAPI.Models
{
    public partial class Comments
    {
        public int Id { get; set; }
        public int Uid { get; set; }
        public int PostId { get; set; }
        public string Comment { get; set; }

        // Below was generated by scaffolding to represent our Foreign Keys
        // DO NOT REMOVE. THE DB CONTEXT USES THEM

        public virtual Posts Post { get; set; }
        public virtual Users U { get; set; }
    }
}
`